import { WordEntry } from './types';

const rawData: [string, 'synonym' | 'antonym', string, string][] = [
  ["progress", "synonym", "advancement / improvement", "অগ্রগতি / উন্নতি"],
  ["efforts", "synonym", "attempts / endeavors", "প্রচেষ্টা / চেষ্টা"],
  ["interest", "synonym", "eagerness / curiosity", "আগ্রহ / কৌতূহল"],
  ["struggle", "antonym", "ease / comfort", "সংগ্রাম ↔ সহজতা"],
  ["dull", "antonym", "lively / interesting", "নিস্তেজ ↔ প্রাণবন্ত"],
  ["competition", "synonym", "contest / rivalry", "প্রতিযোগিতা"],
  ["easily", "antonym", "difficulty", "সহজে ↔ কষ্টে"],
  ["win", "antonym", "lose", "জয় ↔ পরাজয়"],
  ["enjoyment", "synonym", "pleasure / delight", "আনন্দ / উপভোগ"],
  ["victory", "antonym", "defeat", "বিজয় ↔ পরাজয়"],
  ["real", "synonym", "genuine / actual", "বাস্তব / প্রকৃত"],
  ["equally", "antonym", "unequally / unevenly", "সমানভাবে ↔ অসমানভাবে"],
  ["like", "synonym", "prefer / love", "পছন্দ করা"],
  ["continuous", "antonym", "discontinuous / interrupted", "ক্রমাগত ↔ বিচ্ছিন্ন"],
  ["people", "synonym", "individuals / persons", "মানুষ / ব্যক্তিবর্গ"],
  ["conservative", "antonym", "liberal / progressive", "রক্ষণশীল ↔ উদারপন্থী"],
  ["early", "antonym", "late", "তাড়াতাড়ি ↔ দেরিতে"],
  ["believe", "synonym", "trust / accept", "বিশ্বাস করা"],
  ["world", "synonym", "universe / earth", "পৃথিবী / বিশ্ব"],
  ["poverty", "antonym", "richness / wealth", "দারিদ্র্য ↔ সম্পদ"],
  ["much", "antonym", "little / few", "অনেক ↔ সামান্য"],
  ["overcome", "synonym", "conquer / prevail", "জয় করা / কাটিয়ে ওঠা"],
  ["same", "antonym", "different", "একই ↔ ভিন্ন"],
  ["sufferings", "synonym", "miseries / hardships", "কষ্ট / যন্ত্রণা"],
  ["all", "synonym", "none (antonym context)", "সব / কেউ না"],
  ["illness", "synonym", "sickness / ailment", "অসুস্থতা"],
  ["disease", "antonym", "wellness / fitness", "রোগ ↔ সুস্থতা"],
  ["attitude", "synonym", "outlook / opinion", "মনোভাব / দৃষ্টিভঙ্গি"],
  ["forgive", "synonym", "pardon / excuse", "ক্ষমা করা"],
  ["considered", "antonym", "ignored / disregarded", "মনে করা হয় ↔ উপেক্ষিত"],
  ["strength", "antonym", "weakness", "শক্তি ↔ দুর্বলতা"],
  ["resentment", "synonym", "grudge / bitterness", "বিরক্তি / ক্রোধ"],
  ["vengeance", "synonym", "revenge / retaliation", "প্রতিশোধ"],
  ["character", "synonym", "personality / nature", "চরিত্র / ব্যক্তিত্ব"],
  ["restrain", "synonym", "protect / control", "নিয়ন্ত্রণ করা"],
  ["passions", "antonym", "indifference / apathy", "আবেগ ↔ উদাসীনতা"],
  ["superior", "antonym", "inferior", "উচ্চতর ↔ নিম্নতর"],
  ["shame", "synonym", "humiliation / disgrace", "লজ্জা / অপমান"],
  ["forgiveness", "antonym", "vengeance / revenge", "ক্ষমা ↔ প্রতিশোধ"],
  ["foe", "antonym", "friend", "শত্রু ↔ বন্ধু"],
  ["mercy", "antonym", "cruelty", "দয়া ↔ নিষ্ঠুরতা"],
  ["revenge", "synonym", "retribution / retaliation", "প্রতিশোধ"],
  ["sincerity", "antonym", "insincerity / dishonesty", "আন্তরিকতা ↔ কপটতা"],
  ["success", "antonym", "failure", "সাফল্য ↔ ব্যর্থতা"],
  ["job", "synonym", "work / task", "কাজ / চাকরি"],
  ["great", "antonym", "ordinary / small", "মহান ↔ সাধারণ"],
  ["because", "synonym", "as / since", "কারণ"],
  ["know", "synonym", "realize / learn / apprehend", "জানা / বোঝা"],
  ["follow", "antonym", "disobey / ignore", "অনুসরণ করা ↔ অমান্য করা"],
  ["key", "synonym", "way / tool", "চাবি / উপায়"],
  ["never", "synonym", "not / nope", "কখনো না"],
  ["long", "antonym", "short / brief", "দীর্ঘ ↔ সংক্ষিপ্ত"],
  ["victory", "synonym", "triumph", "বিজয় / সাফল্য"],
  ["rules", "synonym", "laws / codes", "নিয়মকানুন"],
  ["desirable", "antonym", "undesirable", "কাম্য ↔ অকাম্য"],
  ["output", "synonym", "result / outcome", "ফলাফল / উৎপাদন"],
  ["used", "antonym", "unused", "ব্যবহৃত ↔ অব্যবহৃত"],
  ["smooth", "antonym", "stiff / rough / uneven", "মসৃণ ↔ রুক্ষ"],
  ["international", "antonym", "local / national", "আন্তর্জাতিক ↔ স্থানীয়"],
  ["prestige", "synonym", "status / fame / honor", "মর্যাদা / সম্মান"],
  ["familiar", "antonym", "unfamiliar / strange", "পরিচিত ↔ অপরিচিত"],
  ["educated", "synonym", "schooled / civilized", "শিক্ষিত"],
  ["whole", "synonym", "entire / complete", "সম্পূর্ণ"],
  ["modern", "antonym", "outdated / ancient", "আধুনিক ↔ পুরাতন"],
  ["knowledge", "antonym", "negligence / ignorance", "জ্ঞান ↔ অজ্ঞতা"],
  ["trade", "synonym", "exchange / business", "বাণিজ্য / ব্যবসা"],
  ["highly", "synonym", "greatly", "অত্যন্ত / ব্যাপকভাবে"],
  ["continue", "antonym", "discontinue", "অব্যাহত রাখা ↔ বন্ধ করা"],
  ["realise", "synonym", "understand / comprehend", "বুঝতে পারা / উপলব্ধি করা"],
  ["important", "synonym", "significant", "গুরুত্বপূর্ণ"],
  ["importance", "antonym", "insignificance / unimportance", "গুরুত্ব ↔ তুচ্ছতা"],
  ["sphere", "synonym", "field / domain / arena", "ক্ষেত্র / অঙ্গন"],
  ["dominate", "synonym", "control / rule", "আধিপত্য করা"],
  ["confined", "synonym", "restricted / limited", "সীমাবদ্ধ"],
  ["walls", "synonym", "barriers / hurdles", "দেওয়াল / বাধা"],
  ["house", "synonym", "home / dwelling", "বাড়ি / গৃহ"],
  ["education", "antonym", "ignorance", "শিক্ষা ↔ অজ্ঞতা"],
  ["able", "antonym", "unable / incapable", "সক্ষম ↔ অক্ষম"],
  ["worth", "synonym", "value / merit", "মূল্য / যোগ্যতা"],
  ["economy", "synonym", "wealth / finance", "অর্থনীতি / সম্পদ"],
  ["realization", "synonym", "awareness", "উপলব্ধি / সচেতনতা"],
  ["never", "antonym", "always", "কখনো না ↔ সবসময়"],
  ["population", "synonym", "people / demography", "জনসংখ্যা"],
  ["condition", "synonym", "situation / state", "অবস্থা"],
  ["value", "synonym", "standard / worth", "মূল্য / মান"],
  ["contribution", "synonym", "participation / achievement", "অবদান"],
  ["unrecognized", "antonym", "recognized", "অস্বীকৃত ↔ স্বীকৃত"],
  ["usually", "synonym", "generally / typically", "সাধারণত"],
  ["voluntary", "synonym", "spontaneous / willing", "স্বেচ্ছামূলক"],
  ["cost", "synonym", "charge / price", "মূল্য / খরচ"],
  ["rural", "antonym", "urban", "গ্রামীণ ↔ শহুরে"],
  ["revealed", "antonym", "concealed", "প্রকাশিত ↔ লুকানো"],
  ["research", "synonym", "study / analysis", "গবেষণা"],
  ["monetized", "antonym", "unpaid", "অর্থায়িত ↔ অপরিশোধিত"],
  ["significant", "antonym", "insignificant", "গুরুত্বপূর্ণ ↔ তুচ্ছ"],
  ["worth", "antonym", "worthless", "মূল্য ↔ মূল্যহীন"],
  ["economy", "synonym", "market", "অর্থনীতি / বাজার"],
  ["dramatically", "antonym", "mildly / subtly", "নাটকীয়ভাবে ↔ মৃদুভাবে"],
  ["symbol", "synonym", "sign / emblem", "প্রতীক / চিহ্ন"],
  ["foundation", "synonym", "base / groundwork", "ভিত্তি"],
  ["entire", "antonym", "partial", "সম্পূর্ণ ↔ আংশিক"],
  ["cover", "antonym", "exclude", "আবরণ ↔ বাদ দেওয়া"],
  ["include", "antonym", "exclude", "অন্তর্ভুক্ত ↔ বাদ দেওয়া"],
  ["preserve", "antonym", "damage / ruin", "সংরক্ষণ ↔ ধ্বংস"],
  ["represent", "synonym", "symbolize", "প্রতিনিধিত্ব করা"],
  ["sacrifice", "synonym", "offering / dedication", "আত্মত্যাগ / উৎসর্গ"],
  ["height", "synonym", "magnitude / altitude", "উচ্চতা"],
  ["before", "antonym", "behind", "আগে ↔ পরে"],
  ["graves", "synonym", "burials / tombs", "কবর"],
  ["bow", "synonym", "bend", "মাथा নোয়ানো"],
  ["respect", "antonym", "disrespect", "সম্মান ↔ অসম্মান"],
  ["blessed", "antonym", "cursed", "আশীর্বাদপ্রাপ্ত ↔ অভিশপ্ত"],
  ["huge", "synonym", "large / big", "বিশাল / বড়"],
  ["open", "antonym", "close / restricted", "উন্মুক্ত ↔ বন্ধ"],
  ["resource", "synonym", "source / reserve", "সম্পদ"],
  ["numerous", "synonym", "many / multitude", "অনেক / প্রচুর"],
  ["area", "synonym", "region / zone", "এলাকা / অঞ্চল"],
  ["vast", "antonym", "small / tiny", "বিস্তৃত ↔ ক্ষুদ্র"],
  ["major", "synonym", "important / significant", "প্রধান / গুরুত্বপূর্ণ"],
  ["supports", "antonym", "hinders / obstructs", "সমর্থন করা ↔ বাধা দেওয়া"],
  ["provides", "synonym", "supplies / offers", "সরবরাহ করা"],
  ["benefit", "synonym", "help / aid", "সুবিধা / উপকার"],
  ["nearly", "antonym", "entirely", "প্রায় ↔ সম্পূর্ণরূপে"],
  ["critical", "antonym", "trivial / unimportant", "সমালোচনামূলক ↔ তুচ্ছ"],
  ["important", "antonym", "unimportant / insignificant", "গুরুত্বপূর্ণ ↔ তুচ্ছ"],
  ["easy", "antonym", "difficult / hard", "সহজ ↔ কঠিন"],
  ["difficult", "synonym", "hard / tough", "কঠিন"],
  ["discover", "synonym", "find / uncover", "আবিষ্কার করা"],
  ["pleasurable", "antonym", "unpleasant", "আনন্দদায়ক ↔ অপ্রীতিকর"],
  ["kindness", "antonym", "cruelty", "দয়া ↔ নিষ্ঠুরতা"],
  ["independent", "antonym", "dependent", "স্বাধীন ↔ নির্ভরশীল"],
  ["universal", "synonym", "global", "সর্বজনীন / বৈশ্বিক"],
  ["perception", "synonym", "view / attitude", "উপলব্ধি / দৃষ্টিভঙ্গি"],
  ["beholder", "synonym", "viewer / spectator", "দর্শক"],
  ["arise", "synonym", "disappear (antonym context)", "উদ্ভব হওয়া"],
  ["manifest", "synonym", "showcase / display", "প্রকাশ পাওয়া"],
  ["presence", "antonym", "absence", "উপস্থিতি ↔ অনুপস্থিতি"],
  ["ugliness", "antonym", "beauty / elegance", "কুৎসিততা ↔ সৌন্দর্য"],
  ["ideal", "antonym", "imperfect / flawed", "আদর্শ ↔ ত্রুটিপূর্ণ"],
  ["obedient", "antonym", "disobedient / disloyal", "অনুগত ↔ অবাধ্য"],
  ["materialize", "synonym", "actualize / realize", "বাস্তবে পরিণত হওয়া"],
  ["worthy", "synonym", "deserving / worthwhile", "যোগ্য / মূল্যবান"],
  ["derail", "synonym", "slip / crash", "পথ থেকে বিচ্যুত হওয়া"],
  ["right", "synonym", "appropriate / proper", "সদুপযুক্ত / যথাযথ"],
  ["zeal", "synonym", "passion / spirit", "উৎসাহ / প্রবল আগ্রহ"],
  ["devote", "synonym", "dedicate", "নিবেদন করা"],
  ["regular", "antonym", "irregular", "নিয়মিত ↔ অনিয়মিত"],
  ["leisure", "antonym", "duty / work", "অবসর ↔ কর্তব্য"],
  ["frugal", "antonym", "careless / wasteful", "মিতব্যয়ী ↔ অপচয়কারী"],
  ["noble", "antonym", "ordinary / undignified", "মহৎ ↔ সাধারণ"],
  ["squander", "synonym", "expend / waste", "অপচয় করা"],
  ["unfortunately", "antonym", "fortunately / luckily", "দুর্ভাগ্যক্রমে ↔ সৌভাগ্যক্রমে"],
  ["pleasant", "antonym", "unpleasant", "আনন্দদায়ক ↔ অপ্রীতিকর"],
  ["beneficial", "antonym", "detrimental / disadvantageous", "উপকারী ↔ ক্ষতিকর"],
  ["regularly", "antonym", "irregularly", "নিয়মিতভাবে ↔ অনিয়মিতভাবে"],
  ["advisable", "synonym", "recommendable / suggestable", "পরামর্শযোগ্য"],
  ["appear", "synonym", "look / emerge", "দেখা যাওয়া / উদয় হওয়া"],
  ["best", "antonym", "worst", "সেরা ↔ সবচেয়ে খারাপ"],
  ["quiet", "antonym", "loud", "শান্ত ↔ কোলাহলপূর্ণ"],
  ["environment", "synonym", "surroundings / atmosphere", "পরিবেশ"],
  ["beasts", "synonym", "monsters / wild animals", "পশু / বন্য প্রাণী"],
  ["serene", "synonym", "calm / peaceful", "প্রশান্ত / শান্ত"],
  ["impressed", "synonym", "fascinated", "মুগ্ধ"],
  ["jovial", "antonym", "gloomy", "প্রফুল্ল ↔ বিষণ্ণ"],
  ["temper", "synonym", "mood / self-control", "মেজাজ"],
  ["rest", "antonym", "end / finished", "বিশ্রাম / বাকি অংশ"],
  ["mentor", "synonym", "guide / instructor", "পরামর্শদাতা / গুরু"],
  ["weak", "antonym", "strong", "দুর্বল ↔ শক্তিশালী"],
  ["discourage", "antonym", "encourage", "নিরুৎসাহিত করা ↔ উৎসাহিত করা"],
  ["frustrating", "synonym", "demoralising / disturbing", "হতাশাজনক"],
  ["ability", "antonym", "inability / incapacity", "দক্ষতা ↔ অক্ষমতা"],
  ["achieve", "synonym", "gain / secure", "অর্জন করা"],
  ["dream", "synonym", "aim / goal", "স্বপ্ন / লক্ষ্য"],
  ["growth", "synonym", "development / upbringing", "বৃদ্ধি / বিকাশ"],
  ["countless", "synonym", "innumerable / numerous", "অসংখ্য"],
  ["instruct", "antonym", "misguide / mislead", "নির্দেশ দেওয়া ↔ ভুল পথে নেওয়া"],
  ["different", "antonym", "similar / same", "ভিন্ন ↔ একই"],
  ["method", "synonym", "process / system", "পদ্ধতি"],
  ["develop", "antonym", "degrade / decline", "উন্নত করা ↔ অবনত হওয়া"],
  ["observation", "synonym", "examination / watching", "পর্যবেক্ষণ"],
  ["curious", "synonym", "inquisitive / interested", "কৌতূহলী"],
  ["mere", "synonym", "only", "নিছক / শুধুমাত্র"],
  ["latent", "synonym", "hidden / concealed", "সুপ্ত / লুকানো"],
  ["alert", "antonym", "indifferent", "সতর্ক ↔ উদাসীন"],
  ["talent", "synonym", "intelligence / brilliance", "প্রতিভা"],
  ["support", "antonym", "oppose / contradict", "সমর্থন ↔ বিরোধিতা"],
  ["common", "antonym", "rare", "সাধারণ ↔ বিরল"],
  ["calamities", "synonym", "disasters / catastrophes", "দুর্যোগ / বিপদ"],
  ["violent", "synonym", "fierce / intense", "হিংসাত্মক / তীব্র"],
  ["deep", "antonym", "shallow", "গভীর ↔ অগভীর"],
  ["inside", "antonym", "outside", "ভেতরে ↔ বাইরে"],
  ["chance", "synonym", "probability / opportunity", "সুযোগ / সম্ভাবনা"],
  ["occur", "synonym", "happen", "ঘটা"],
  ["active", "antonym", "inactive", "সক্রিয় ↔ নিষ্ক্রিয়"],
  ["frequently", "antonym", "rarely / seldom", "প্রায়ই ↔ বিরলে"],
  ["responsible", "antonym", "irresponsible", "দায়িত্বশীল ↔ দায়িত্বহীন"],
  ["development", "synonym", "growth / progress", "উন্নয়ন / বিকাশ"],
  ["reduce", "antonym", "increase", "কমানো ↔ বাড়ানো"],
  ["aware", "synonym", "conscious", "সচেতন / ওয়াকিফহাল"],
  ["gravity", "synonym", "seriousness", "গুরুত্ব / গুরুতরতা"],
  ["dangerous", "synonym", "hazardous", "বিপজ্জনক"],
  ["mortifying", "antonym", "delightful / pleasing", "লজ্জাজনক ↔ আনন্দদায়ক"],
  ["cause", "synonym", "make / bring about", "কারণ হওয়া"],
  ["poisonous", "synonym", "venomous / toxic", "বিষাক্ত"],
  ["fatal", "antonym", "harmless", "মারাত্মক ↔ ক্ষতিহীন"],
  ["injurious", "synonym", "harmful / detrimental", "ক্ষতিকর"],
  ["impede", "synonym", "obstruct / interrupt", "বাধা দেওয়া"],
  ["normal", "synonym", "simple / common / usual", "স্বাভাবিক"],
  ["hinder", "synonym", "assist / support (antonym)", "বাধা দেওয়া"],
  ["unlimited", "antonym", "limited", "সীমাহীন ↔ সীমিত"],
  ["avoid", "antonym", "confront / face", "এড়িয়ে চলা ↔ মোকাবেলা করা"],
  ["peaceful", "antonym", "chaotic / turbulent", "শান্তিময় ↔ বিশৃঙ্খল"],
  ["outcome", "synonym", "result", "ফলাফল"],
  ["intention", "synonym", "purpose", "উদ্দেশ্য / অভিপ্রায়"],
  ["trust", "antonym", "distrust / doubt", "বিশ্বাস ↔ অবিশ্বাস"],
  ["eager", "antonym", "reluctant / uninterested", "আগ্রহী ↔ অনিচ্ছুক"],
  ["prove", "synonym", "demonstrate", "প্রমাণ করা"],
  ["deed", "synonym", "action", "কাজ / কর্ম"],
  ["praise", "antonym", "criticism / criticize", "প্রশংসা ↔ সমালোচনা"],
  ["sincere", "synonym", "honest", "আন্তরিক / সৎ"],
  ["harmful", "synonym", "detrimental", "ক্ষতিকর"],
  ["cabin", "synonym", "compartment", "কেবিন / কক্ষ"],
  ["logic", "antonym", "absurdity / irrationality", "যুক্তি ↔ অযৌক্তিকতা"],
  ["clear", "antonym", "vague / unclear", "স্পষ্ট ↔ অস্পষ্ট"],
  ["money", "synonym", "penny / currency", "অর্থ / টাকা"],
  ["ill", "antonym", "well / healthy", "অসুস্থ ↔ সুস্থ"],
  ["many", "synonym", "numerous", "অনেক"],
  ["passive", "antonym", "active", "নিষ্ক্রিয় ↔ সক্রিয়"],
  ["incurable", "antonym", "curable", "নিরাময়যোগ্য নয় ↔ নিরাময়যোগ্য"],
  ["more", "synonym", "additional / extra", "আরও বেশি"],
  ["enjoyable", "antonym", "unpleasant", "উপভোগ্য ↔ অপ্রীতিকর"],
  ["good", "antonym", "bad / evil", "ভালো ↔ মন্দ"],
  ["writer", "synonym", "author", "লেখক"],
  ["speaker", "synonym", "lecturer / orator", "বক্তা"],
  ["recitation", "synonym", "reading / study", "আবৃত্তি / পাঠ"],
  ["impossible", "antonym", "possible / feasible", "অসম্ভব ↔ সম্ভব"],
  ["lazy", "antonym", "active / diligent / energetic", "অলস ↔ পরিশ্রমী"],
  ["main", "antonym", "minor", "প্রধান ↔ গৌণ"],
  ["sincerity", "synonym", "honesty / cordiality", "আন্তরিকতা"],
  ["seriousness", "synonym", "gravity / stiffness", "গুরুতরতা / গম্ভীরতা"],
  ["consideration", "synonym", "thoughtful / deliberation", "বিবেচনা"],
  ["serious", "antonym", "playful / unwise / frivolous", "গুরুতর ↔ হালকা"],
  ["possible", "antonym", "impossible / implausible", "সম্ভব ↔ অসম্ভব"],
  ["shine", "synonym", "shimmer / glaze / sparkle", "উজ্জ্বল হওয়া / চকচক করা"],
  ["optimistic", "antonym", "hopeless / pessimistic", "আশাবাদী ↔ হতাশাবাদী"],
  ["hard", "synonym", "heavily / arduously", "কঠিন / পরিশ্রমসাধ্য"],
  ["guidelines", "synonym", "principles / rules / advices", "নির্দেশিকা / পথনির্দেশ"],
  ["understand", "synonym", "perceive / comprehend / realize", "বোঝা / উপলব্ধি করা"],
  ["diligent", "synonym", "industrious / persevering", "পরিশ্রমী / অধ্যবসায়ী"],
  ["rely", "synonym", "depend / lean", "নির্ভর করা"],
  ["honesty", "antonym", "dishonesty / fraud / deception", "সততা ↔ অসততা"],
  ["help", "antonym", "hinder / obstruct / hamper", "সাহায্য ↔ বাধা"],
  ["peak", "synonym", "zenith / summit / pinnacle", "শিখর / চূড়া"],
  ["laborious", "antonym", "lazy / idle / lethargic", "কঠোর পরিশ্রমী ↔ অলস"],
  ["harbour", "synonym", "shield / hold / cherish", "আশ্রয় দেওয়া / পোষণ করা"],
  ["popular", "antonym", "unpopular / unknown / ignored", "জনপ্রিয় ↔ অজনপ্রিয়"],
  ["effects", "synonym", "consequences / impacts / outcomes", "প্রप्रभाव / ফলাফল"],
  ["touch", "synonym", "contact / connection / communication", "যোগাযোগ / স্পর্শ"],
  ["friends", "antonym", "enemies / unknowns / strangers", "বন্ধু ↔ শত্রু"],
  ["means", "synonym", "media / ways / modes / paths", "উপায় / মাধ্যম"],
  ["connected", "antonym", "disconnected / separated", "সংযুক্ত ↔ বিচ্ছিন্ন"],
  ["make", "synonym", "build / establish / generate", "তৈরি করা"],
  ["unknown", "antonym", "familiar / known / recognized", "অজানা ↔ পরিচিত"],
  ["thrive", "synonym", "expand / increase / grow / spread", "উন্নতি করা / বৃদ্ধি পাওয়া"],
  ["harass", "synonym", "tease / disturb / infest / embarrass", "হয়রানি করা"],
  ["teenager", "antonym", "old / matured / adult / grown-up", "কিশোর ↔ প্রবীণ"],
  ["spend", "synonym", "pass / waste / consume", "ব্যয় করা"],
  ["hospitality", "synonym", "friendliness / generosity / cordiality", "আতিথেয়তা / আন্তরিকতা"],
  ["friendly", "antonym", "hostile / unfavorable", "বন্ধুত্বপূর্ণ ↔ বৈরী"],
  ["generous", "synonym", "kind / magnanimous / noble", "উদার / দানশীল"],
  ["treatment", "synonym", "behaviour / reception / conduct", "আচরণ / চিকিৎসা"],
  ["entertainment", "antonym", "bore / grief / indifference / ignorance", "বিনোদন ↔ বিরক্তি"],
  ["stranger", "antonym", "known / familiar / friend / acquainted", "অপরিচিত ↔ পরিচিত"],
  ["encourage", "synonym", "inspire / motivate / uplift / cheer", "উৎসাহিত করা"],
  ["travel", "synonym", "visit / roam / wonder", "ভ্রমণ করা"],
  ["having", "synonym", "owning / holding / possessing / retaining", "থাকা / অধিকারে রাখা"],
  ["self-centred", "antonym", "considerate / liberal / sympathetic", "আত্মকেন্দ্রিক ↔ পরোপকারী"],
  ["etiquette", "synonym", "manner / behaviour / protocol / courtesy", "শিষ্টাচার"],
  ["peace", "antonym", "disorder / conflict / irritation / distress", "শান্তি ↔ অশান্তি"],
  ["amity", "antonym", "animosity / enmity / hostility", "বন্ধুত্ব ↔ শত্রুতা"],
  ["cultivate", "synonym", "practice / exercise / execute / apply / utilize", "চর্চা করা / গড়ে তোলা"],
  ["illiterate", "antonym", "educated / literate / taught / learned", "অশিক্ষিত ↔ শিক্ষিত"],
  ["retards", "synonym", "resists / hinders / delays / slows", "পিছিয়ে দেওয়া / ধীর করা"],
  ["darkness", "antonym", "light / brightness / shining / gleaming", "অন্ধকার ↔ আলো"],
  ["goal", "synonym", "aim / target / ambition / objective", "লক্ষ্য / উদ্দেশ্য"],
  ["unconscious", "synonym", "ignorant / indifferent / uninformed / insensible", "অচেতন / অজ্ঞ"],
  ["responsibility", "synonym", "duties / obligations / commitments", "দায়িত্ব / কর্তব্য"],
  ["poor", "antonym", "rich / solvent / affluent / wealthy", "দরিদ্র ↔ ধনী"],
  ["measures", "synonym", "step / action / act / deed / programme", "পদক্ষেপ / ব্যবস্থা"],
  ["remove", "synonym", "eradicate / uproot / eliminate / abolish", "অপসারণ করা / দূর করা"],
  ["basic", "synonym", "fundamental / primary", "মৌলিক / প্রাথমিক"],
  ["essential", "synonym", "important / indispensable / necessary", "অপরিহার্য / প্রয়োজনীয়"],
  ["inaccessibility", "antonym", "accessibility / availability / affordability", "দুর্গমতা ↔ সহজলভ্যতা"],
  ["sanitation", "synonym", "cleanliness / hygiene / disinfection", "পয়ঃনিষ্কাশন / পরিচ্ছন্নতা"],
  ["healthy", "antonym", "unhealthy / unsound / harmful / detrimental", "সুস্থ ↔ অস্বাস্থ্যকর"],
  ["teach", "antonym", "mislead / misguide / misinform / misdirect / withhold", "শেখানো ↔ ভুল শেখানো"],
  ["spend", "antonym", "save / hold / preserve / keep / hoard", "ব্যয় করা ↔ সঞ্চয় করা"],
  ["properly", "synonym", "exactly / genuinely / accurately / appropriately", "সঠিকভাবে"],
  ["enable", "antonym", "inability / incompetence / incapability / incapacity", "সক্ষম করা ↔ অক্ষমতা"],
  ["good-looking", "synonym", "beautiful / pretty", "সুদর্শন / সুন্দর"],
  ["dark", "synonym", "black / sable", "কালো / অন্ধকার"],
  ["flawless", "synonym", "perfect / immaculate / fine", "নিখুঁत / ত্রুটিহীন"],
  ["shiny", "antonym", "unglazed / dim / dull", "চকচকে ↔ নিস্তেজ"],
  ["slender", "antonym", "fat / thick", "পাতলা ↔ মোটা"],
  ["graceful", "synonym", "elegant / charming / pleasant", "মার্জিত / কমনীয়"],
  ["stylishly", "antonym", "unfashionably / unstylishly / obsoletely", "ফ্যাশনেবলভাবে ↔ পুরনো ধাঁচে"],
  ["appreciate", "antonym", "undermine / ignore / disparage / belittle / criticize", "মূল্যায়ন করা ↔ অবমূল্যায়ন করা"],
  ["worries", "antonym", "enjoys / cheers", "চিন্তা করা ↔ উপভোগ করা"],
  ["notice", "antonym", "ignore / dismiss / disregard", "লক্ষ্য করা ↔ উপেক্ষা করা"],
  ["beauty", "antonym", "ugliness / wickedness / filthiness", "সৌন্দর্য ↔ কুৎসিততা"],
  ["ambition", "synonym", "aspiration / dream / target / aim", "উচ্চাকাঙ্ক্ষা"],
  ["intelligence", "synonym", "talent / brilliance", "বুদ্ধিমত্তা / মেধা"],
  ["curse", "antonym", "blessing / boon / gift / grace", "অভিশাপ ↔ আশীর্বাদ"],
  ["enlightened", "synonym", "educated / cultured", "আকালো / শিক্ষিত"],
  ["outer", "antonym", "inner", "বাইরের ↔ ভেতরের"],
  ["proletarian", "synonym", "common / ordinary / working-class", "সর্বহারা / সাধারণ"],
  ["launch", "synonym", "install / begin / inaugurate / establish / initiate", "উৎক্ষেপণ / চালু করা"],
  ["prepare", "synonym", "ready / arrange", "প্রস্তুত করা"],
  ["began", "antonym", "ended / completed", "শুরু হয়েছিল ↔ শেষ হয়েছিল"],
  ["faultless", "antonym", "faulty / imperfect", "নিখুঁত ↔ ত্রুটিপূর্ণ"],
  ["nausea", "synonym", "vomiting tendency / sickness / queasiness", "বমি বমি ভাব"],
  ["discomfort", "antonym", "comfort", "অস্বস্তি ↔ আরাম"],
  ["maintain", "synonym", "keep / continue", "বজায় রাখা"],
  ["later", "antonym", "early / before", "পরে ↔ আগে"],
  ["dynamic", "antonym", "lethargic / static", "গতিশীল ↔ স্থির"],
  ["plan", "antonym", "aimlessness / purposelessness", "পরিকল্পনা ↔ উদ্দেশ্যহীনতা"],
  ["aim", "synonym", "goal / purpose", "লক্ষ্য / উদ্দেশ্য"],
  ["direction", "synonym", "way / manner / course / trend", "দিকনির্দেশনা"],
  ["profession", "synonym", "career / occupation / job", "পেশা"],
  ["suit", "antonym", "mismatch / contradict / misfit", "উপযুক্ত ↔ অনুপযুক্ত"],
  ["aptitude", "antonym", "disability / inability / incapacity", "যোগ্যতা ↔ অক্ষমতা"],
  ["vary", "synonym", "differ / contrast / alter / change", "পরিবর্তিত হওয়া / ভিন্ন হওয়া"],
  ["educate", "synonym", "teach / coach / train", "শিক্ষিত করা"],
  ["citizen", "antonym", "foreigner / non-resident", "নাগরিক ↔ বিদেশি"],
  ["fascinating", "antonym", "boring / repel / unattractive", "আকর্ষণীয় ↔ বিরক্তিকর"],
  ["impatient", "antonym", "patient / calm / tolerant", "অধৈর্য ↔ ধৈর্যশীল"],
  ["immoral", "synonym", "unethical / bad / morally wrong", "অনৈতিক"],
  ["contain", "synonym", "hold / accommodate", "ধারণ করা"],
  ["illogical", "antonym", "logical / rational", "অযৌক্তিক ↔ যৌক্তিক"],
  ["indifferent", "synonym", "unconcerned / apathetic / uncaring / uninterested", "উদাসীন"],
  ["perfect", "antonym", "imperfect / faulty / defective / flawed", "নিখুঁত ↔ ত্রুটিপূর্ণ"],
  ["instructive", "synonym", "informative / instructional / informational", "শিক্ষামূলক"],
  ["ethical", "antonym", "unethical / lawless", "নৈতিক ↔ অনৈতিক"],
  ["require", "synonym", "need / requisite", "প্রয়োজন হওয়া"],
  ["proficiency", "antonym", "incompetence / ineptness / deficiency", "দক্ষতা ↔ অদক্ষতা"],
  ["wonder", "synonym", "admiration / fascination / surprise", "বিস্ময়"],
  ["tested", "synonym", "evaluate / assess / examine / verified", "পরীক্ষিত"],
  ["disappointing", "synonym", "disheartening / saddening / unsatisfactory", "হতাশাজনক"],
  ["presumably", "antonym", "doubtfully / dubiously", "সম্ভবত ↔ সন্দেহজনকভাবে"],
  ["qualify", "antonym", "disqualify / fail", "যোগ্যতা অর্জন ↔ অযোগ্য হওয়া"],
  ["obviously", "antonym", "doubtfully / dubiously", "স্পষ্টতই ↔ সন্দেহজনকভাবে"],
  ["wrong", "synonym", "incorrect / inaccurate / erroneous", "ভুল"],
  ["seek", "synonym", "quest / search / pursue", "খোঁজা / সন্ধান করা"],
  ["eager", "antonym", "uninterested / apathetic", "আগ্রহী ↔ অনাগ্রহী"],
  ["mere", "antonym", "enormous / great", "নিছক ↔ বিরাট"],
  ["alert", "synonym", "aware / watchful / attentive / vigilant", "সতর্ক / সজাগ"],
  ["latent", "antonym", "active / manifest / open / exposed", "সুপ্ত ↔ প্রকাশিত"],
  ["instructor", "synonym", "mentor / teacher", "শিক্ষক / প্রশিক্ষক"],
  ["way", "synonym", "path / road", "উপায় / পথ"],
  ["virtue", "synonym", "goodness / morality", "গুণ / সদগুণ"],
  ["a lot", "synonym", "many / enormous / huge", "অনেক"],
  ["courteous", "antonym", "discourteous / rude", "ভদ্র ↔ অভদ্র"],
  ["discourtesy", "synonym", "rudeness / unaffectionateness", "অভদ্রতা"],
  ["enemy", "synonym", "adversary / antagonist / foe / opponent", "শত্রু"],
  ["ensure", "synonym", "secure / guarantee / confirm", "নিশ্চিত করা"],
  ["anger", "antonym", "pleasure / calmness", "রাগ ↔ শান্তি"],
  ["cordiality", "antonym", "rudeness / conflict / irritation / distress", "বন্ধুত্ব ↔ রুক্ষতা"],
  ["freedom", "synonym", "liberation / independence", "স্বাধীনতা / মুক্তি"],
  ["devoted", "synonym", "dedicated / committed", "নিবেদিতপ্রাণ"],
  ["heritage", "synonym", "culture / tradition", "ঐতিহ্য / সংস্কৃতি"],
  ["justice", "antonym", "injustice", "ন্যায়বিচার ↔ অবিচার"],
  ["valuable", "antonym", "cheap / inexpensive", "মূল্যবান ↔ সস্তা"],
  ["unique", "antonym", "usual / general", "অনন্য ↔ সাধারণ"],
  ["mighty", "antonym", "weak / powerless", "শক্তিশালী ↔ দুর্বল"],
  ["reliable", "antonym", "unreliable", "বিশ্বস্ত ↔ অবিশ্বস্ত"],
  ["humanity", "synonym", "compassion / mercy", "মানবতা"],
  ["ritual", "synonym", "ceremonial / customary", "আচার / প্রথা"],
  ["loneliness", "synonym", "lonesomeness / solitude / solitariness", "একাকীত্ব"],
  ["worthless", "synonym", "valueless / useless", "মূল্যহীন / অকেজো"],
  ["happiness", "antonym", "sorrow / grief / unhappiness", "সুখ ↔ দুঃখ"],
  ["need", "antonym", "optional", "প্রয়োজন ↔ ঐচ্ছিক"],
  ["harm", "antonym", "benefit / help / good", "ক্ষতি ↔ উপকার"],
  ["sympathy", "synonym", "compassion / pity / mercy", "সহানুভূতি"],
  ["false", "antonym", "genuine / real / true", "মিথ্যা ↔ সত্য"],
  ["bring", "synonym", "fetch / give / convey", "আনা / বহন করা"],
  ["laugh", "antonym", "cry / weep", "হাসা ↔ কাঁদা"],
  ["pleasure", "synonym", "joy / delight", "আনন্দ / সুখ"],
  ["idea", "synonym", "notion / concept / thought", "ধারণা"],
  ["everlasting", "synonym", "eternal / constant / perpetual", "চিরস্থায়ী"],
  ["throughout", "synonym", "during / all through / all", "জুড়ে / সর্বত্র"],
  ["life", "antonym", "death", "জীবন ↔ মৃত্যু"],
  ["form", "synonym", "shape", "রূপ / আকার"],
  ["entertainment", "synonym", "amusement", "বিনোদন"],
  ["organize", "synonym", "arrange", "সংগঠিত করা / আয়োজন করা"],
  ["sponsor", "synonym", "patron / donor", "পৃষ্ঠপোষক"],
  ["multinational", "antonym", "national", "বহুজাতিক ↔ জাতীয়"],
  ["pay", "antonym", "owe", "পরিশোধ করা ↔ ঋণী থাকা"],
  ["watch", "synonym", "observe", "দেখা / পর্যবেক্ষণ করা"],
  ["maximum", "antonym", "minimum", "সর্বোচ্চ ↔ সর্বনিম্ন"],
  ["recognition", "antonym", "cancellation", "স্বীকৃতি ↔ বাতিল"],
  ["recently", "synonym", "lately", "সম্প্রতি"],
  ["rise", "antonym", "fall", "বৃদ্ধি ↔ পতন"],
  ["accumulated", "synonym", "amassed / gathered", "সঞ্চিত / জমা"],
  ["flood", "antonym", "drought / trickle", "বন্যা ↔ খরা"],
  ["threat", "synonym", "risk / danger / menace", "হুমকি / বিপদ"],
  ["effect", "synonym", "consequence / outcome", "প্রভাব / ফলাফল"],
  ["primarily", "antonym", "ultimately / finally", "মূলত ↔ শেষ পর্যন্ত"],
  ["eventually", "synonym", "ultimately / finally / lastly", "অবশেষে"],
  ["tropical", "antonym", "temperate / moderate", "গ্রীষ্মমণ্ডলীয় ↔ নাতিশীতোষ্ণ"],
  ["drug", "synonym", "medicine", "ওষধ / মাদক"],
  ["supply", "synonym", "provision / distribution", "সরবরাহ"],
  ["moreover", "synonym", "besides / also", "তদুপরি / ছাড়াও"],
  ["trafficking", "synonym", "smuggling", "পাচার"],
  ["dwellers", "antonym", "gypsys / nomads", "বাসিন্দা ↔ যাযাবর"],
  ["quick", "antonym", "slow", "দ্রুত ↔ ধীর"],
  ["largely", "antonym", "slightly", "অনেকাংশে ↔ সামান্যভাবে"],
  ["misused", "antonym", "utilized / used well", "অপব্যবহার ↔ সঠিক ব্যবহার"],
  ["different", "antonym", "similar / same", "ভিন্ন ↔ একই"],
  ["nation", "synonym", "state / race / country", "জাতি / দেশ"],
  ["importance", "antonym", "unimportance / insignificance", "গুরুত্ব ↔ গুরুত্বহীনতা"],
  ["declare", "synonym", "announce / proclaim", "ঘোষণা করা"],
  ["battle", "synonym", "fight / struggle", "যুদ্ধ / সংগ্রাম"],
  ["freedom", "antonym", "captivity", "স্বাধীনতা ↔ বন্দিত্ব"],
  ["sacrifice", "synonym", "dedicate / offer", "উৎসর্গ করা / আত্মত্যাগ করা"],
  ["identity", "synonym", "individuality / introduction", "পরিচয় / স্বকীয়তা"],
  ["independent", "antonym", "dependent / reliant", "স্বাধীন ↔ নির্ভরশীল"],
  ["liberation", "antonym", "captivity", "মুক্তি ↔ বন্দিত্ব"],
  ["student", "synonym", "learner / pupil", "ছাত্র / শিক্ষার্থী"],
  ["weaker", "antonym", "stronger", "দুর্বলতর ↔ শক্তিশালী"],
  ["frustrating", "synonym", "ignoring / upsetting", "হতাশাজনক"],
  ["interest", "synonym", "curiosity / wish", "আগ্রহ / কৌতূহল"],
  ["ability", "synonym", "capacity / capability", "দক্ষতা / সামর্থ্য"],
  ["guide", "antonym", "misguide", "পরিচালনা ↔ ভুল পথ দেখানো"],
  ["achieve", "synonym", "acquire / earn / attain", "অর্জন করা"],
  ["teacher", "synonym", "mentor / instructor", "শিক্ষক"],
  ["discourage", "antonym", "encourage / acknowledge", "নিরুৎসাহিত করা ↔ উৎসাহিত করা"],
  ["precious", "antonym", "cheap", "মূল্যবান ↔ সস্তা"],
  ["glitter", "synonym", "shine / sparkle", "চকচক করা"],
  ["attract", "synonym", "captivate / fascinate", "আকৃষ্ট করা"],
  ["merits", "synonym", "quality / standard", "যোগ্যতা / গুণ"],
  ["recognize", "synonym", "acknowledge", "স্বীকার করা"],
  ["glamour", "antonym", "dullness / fade", "আকর্ষণ ↔ নিস্তেজতা"],
  ["gentle", "antonym", "unkind / brutal / harsh", "কোমল ↔ নিষ্ঠুর"],
  ["shine", "antonym", "fade", "উজ্জ্বলতা ↔ বিবর্ণতা"],
  ["morality", "antonym", "immorality", "নৈতিকতা ↔ অনৈতিকতা"],
  ["important", "antonym", "unimportant / common", "গুরুত্বপূর্ণ ↔ তুচ্ছ"],
  ["apt", "synonym", "inclined / prone", "উপযুক্ত / প্রবণ"],
  ["burn", "synonym", "ignite / light", "জ্বলা / প্রজ্বলিত হওয়া"],
  ["end", "antonym", "start / beginning", "শেষ ↔ শুরু"],
  ["traffic", "synonym", "passage / communication", "যানজট / যোগাযোগ"],
  ["quicken", "antonym", "decelerate / slow down", "দ্রুত করা ↔ ধীর করা"],
  ["inspire", "synonym", "motivate / encourage", "অনুপ্রাণিত করা"],
  ["loses", "antonym", "gains", "হারানো ↔ লাভ করা"],
  ["wasted", "antonym", "saved / preserved", "নষ্ট ↔ সংরক্ষিত"],
  ["love", "antonym", "hate", "ভালোবাসা ↔ ঘৃণা"],
  ["advancement", "synonym", "progress / development", "অগ্রগতি"],
  ["complicated", "antonym", "easy / simple", "জটিল ↔ সহজ"],
  ["essential", "antonym", "unnecessary / optional", "অপরিহার্য ↔ অপ্রয়োজনীয়"],
  ["perform", "synonym", "accomplish / do", "সম্পাদন করা"],
  ["special", "synonym", "unique / particular", "বিশেষ"],
  ["sector", "synonym", "part / field", "বিভাগ / ক্ষেত্র"],
  ["substitute", "synonym", "replace", "বিকল্প / প্রতিস্থাপন করা"],
  ["large", "antonym", "small / little", "বড় ↔ ছোট"],
  ["energy", "synonym", "strength / power", "শক্তি"],
  ["widely", "antonym", "narrowly / scarcely", "ব্যাপকভাবে ↔ সংকীর্ণভাবে"],
  ["speed", "synonym", "boost / rate", "গতি"],
  ["competence", "synonym", "efficiency / proficiency / skill", "দক্ষতা / যোগ্যতা"],
  ["appropriately", "antonym", "unsuitably / improperly", "উপযুক্তভাবে ↔ অনুপযুক্তভাবে"],
  ["similar", "antonym", "different / distinct", "একই রকম ↔ ভিন্ন"],
  ["natural", "synonym", "innate / inborn", "প্রাকৃতিক / সহজাত"],
  ["communicate", "antonym", "withhold / avoid", "যোগাযোগ করা ↔ এড়িয়ে চলা"],
  ["spontaneously", "synonym", "automatically / naturally", "স্বতঃস্ফূর্তভাবে"],
  ["implicit", "antonym", "explicit", "অস্পষ্ট / অব্যক্ত ↔ স্পষ্ট"],
  ["ways", "synonym", "methods / modes", "উপায় / পদ্ধতি"],
  ["aware", "antonym", "heedless / indifferent", "সচেতন ↔ অসচেতন"],
  ["conflict", "antonym", "peace / harmony", "দ্বন্দ্ব ↔ শান্তি"],
  ["hostility", "antonym", "friendship / kindness", "শত্রুতা ↔ বন্ধুত্ব"],
  ["opposition", "antonym", "accord / agreement", "বিরোধিতা ↔ সম্মতি"],
  ["attempt", "synonym", "effort / try", "চেষ্টা"],
  ["objective", "synonym", "goal / aim", "লক্ষ্য / উদ্দেশ্য"],
  ["principles", "synonym", "rules / ideals", "নীতি / আদর্শ"],
  ["antagonism", "antonym", "friendship", "বিরোধ ↔ বন্ধুত্ব"],
  ["party", "synonym", "group", "দল / গোষ্ঠী"],
  ["elements", "synonym", "features / components", "উপাদান"],
  ["values", "synonym", "ethics", "মূল্যবোধ"]
];

export const wordList: WordEntry[] = rawData.map((item, idx) => ({
  id: `entry-${idx}`,
  word: item[0],
  type: item[1],
  answer: item[2],
  bengali: item[3]
}));
